spring:
  application:
    name: EmployeeService
    
server:
  port: 9101
  
eureka:
  instance:
    hostname: localhost
    

  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
    register-with-eureka: false
    fetch-registry: true

  