spring:
  application:
    name: EmployerService
    
server:
  port: 9102
    
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
    register-with-eureka: true
    fetch-registry: true